new

diff --git a/.github/workflows/check-labels.yml b/.github/workflows/check-labels.yml
--- a/.github/workflows/check-labels.yml
+++ b/.github/workflows/check-labels.yml
@@ -11,31 +11,16 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Check for Required Label
+        if: ${{ contains(fromJson('["devnet-pass"]'), github.event.label.name) != true }}
         run: |
-          echo "A"
-          REQUIRED_LABEL="devnet-pass"
-          echo "B"
-          PR_LABELS=$(echo '${{ toJSON(github.event.pull_request.labels) }}' | tr -d '\n')
-          echo "C"
-
-          if echo "$PR_LABELS" | grep -q "\"name\":\"$REQUIRED_LABEL\""; then
-            echo "D1"
-            echo "Required label '$REQUIRED_LABEL' is present."
-          else:
-            echo "D2"
-            echo "Error: Required label '$REQUIRED_LABEL' is missing."
-            exit 1
+          echo "Error: Required label 'devnet-pass' is missing."
+          exit 1
   testnet-pass:
     name: testnet-pass
     runs-on: ubuntu-latest
     steps:
       - name: Check for Required Label
+        if: ${{ contains(fromJson('["testnet-pass"]'), github.event.label.name) != true }}
         run: |
-          REQUIRED_LABEL="testnet-pass"
-          PR_LABELS='${{ toJSON(github.event.pull_request.labels) }}'
-
-          if echo "$PR_LABELS" | grep -q "\"name\":\"$REQUIRED_LABEL\""; then
-            echo "Required label '$REQUIRED_LABEL' is present."
-          else:
-            echo "Error: Required label '$REQUIRED_LABEL' is missing."
-            exit 1
+          echo "Error: Required label 'testnet-pass' is missing."
+          exit 1
